---
subscription_repo_url: https://github.com/amjedjabari/rosa-automation-hcp
subscription_branch: eso-test-demo
state: present
cluster_admin_service_account_name: ansible-playbook-service-account-cluster-admin
cluster_admin_service_account_namespace: ansible-playbook-access-cluster-admin
acm_service_account_name: ansible-playbook-service-account-acm
acm_service_account_namespace: ansible-playbook-access-acm
...
