apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: test-app
  name: app-secret 
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: app-secret  ##The secret name in ocp that is stored in AWS Secret Manager
        metadataPolicy: None
        property: appuser  ##KEY1
      secretKey: appuser   ##KEY1
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: app-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: app-secret   ##The secret name in ocp that is stored in AWS Secret Manager
---
