apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: app-secret-store
  namespace: test-app  ##NAMESPACE $USER_NAMESPACE (The namespace where the OCP secret is going to be created in)
spec:
  provider:
    aws:
      auth:
        jwt:
          serviceAccountRef:
            name: eso-test-sa   ##The Service Account $SA_NAME that is going to have access to the ocp secret)
            namespace: test-app ##The OpenShift namespace name where the Secret is going to live.
      region: '{{ fromConfigMap "acm-install-policies" "aws-config" "region" }}'
      service: SecretsManager
