---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupSync
metadata:
  name: rosa-groupsync
  namespace: group-sync-operator
spec:
  providers:
    - ldap:
        credentialsSecret:
          kind: Secret
          name: osrosa-ldapbinding
          namespace: group-sync-operator
        caSecret:
          kind: Secret
          name: osrosa-3mcacerts
          namespace: group-sync-operator  
        insecure: false
        rfc2307:
          usersQuery:
            baseDN: 'OU=Mail-Routing,OU=Groups,OU=FAP,O=3M'
            derefAliases: never
            pageSize: 0
            scope: sub
          groupNameAttributes:
            - cn
          tolerateMemberNotFoundErrors: true
          tolerateMemberOutOfScopeErrors: true
          groupUIDAttribute: dn
          groupMembershipAttributes:
            - member
          userNameAttributes:
            - uid
          groupsQuery:
            baseDN: 'xxxxxxx'
            derefAliases: always
            filter: xxxxxxxxxxxxx
            pageSize: 0
            scope: sub
          userUIDAttribute: dn
        url: xxxxxxxxx
      name: ldap
  schedule: 0 * * * *
